version: '2'
services:
  jobmanager:
    image: flink:1.16.0-scala_2.12-java11
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        execution.checkpointing.interval: 5000
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints-directory
        state.savepoints.dir: file:///tmp/flink-savepoints-directory

    volumes:
      - ./flink-lib/flink-sql-connector-kafka-1.16.0.jar:/opt/flink/lib/flink-sql-connector-kafka-1.16.0.jar

  taskmanager:
    image: flink:1.16.0-scala_2.12-java11
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        execution.checkpointing.interval: 5000
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints-directory
        state.savepoints.dir: file:///tmp/flink-savepoints-directory
    volumes:
      - ./flink-lib/flink-sql-connector-kafka-1.16.0.jar:/opt/flink/lib/flink-sql-connector-kafka-1.16.0.jar

  sql-gateway:
    image: flink:1.16.0-scala_2.12-java11
    ports:
      - "8083:8083"
    entrypoint: /bin/sh
    command:
      - -c
      - |
        /docker-entrypoint.sh
        /opt/flink/bin/sql-gateway.sh start-foreground
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        sql-gateway.endpoint.rest.address: 0.0.0.0
    volumes:
      - ./flink-lib/flink-sql-connector-kafka-1.16.0.jar:/opt/flink/lib/flink-sql-connector-kafka-1.16.0.jar

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      TOPIC_AUTO_CREATE: "true"

networks:
  default:
    name: flink
